### PR TITLE
Remove `typescript` from list of languages

### LINKED ISSUE #644: Intellisense should not work in `.ts` files
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**VS Code settings**

```json
// So many settings. Only this setting enabled from extension
{
  "tailwindCSS.emmetCompletions": true,
}
```

**Describe your issue**

HTML or JSX isn't written in `.ts` files. So I think the extension should not show the intellisense in the `.ts` files.
Intellisense works in `.tsx` files and that's good but it shouldn't in `.ts` files

image

### PR DESCRIPTION
**Pull request by max-programming**
I hope this fixes #644

### CODE REVIEW

**Comment by max-programming** [comment]
@bradlc What do you think about this?

**Comment by bradlc** [comment]
I agree that it makes sense to remove this, thanks!

**Comment by SEQUOiA87** [comment]
Ehhh 👀

This removes typescript from the `jsLanguages` constant. Are you sure about this?

I don't specifically know how this constant is used by the plugin, but the fact that:
- typescript is of course a "javascript language" (at least not less than those other languages which are still part of the constant: https://github.com/tailwindlabs/tailwindcss-intellisense/blob/v0.9.2/packages/tailwindcss-language-service/src/util/languages.ts#L49-L52)
- in Angular, it's perfectly fine to define an Angular component's template (HTML) code directly within the component, i.e. within the .ts file (see here: https://angular.io/guide/component-overview#defining-a-components-template)

... let's me think that this change should be reverted.

In the meantime, for anyone needing this plugin to also work in typescript files, putting this into the VS Code settings helps:
```
"tailwindCSS.includeLanguages": {
    "typescript": "javascript"
}
```

**Comment by max-programming** [comment]
Oh I see that now. Sorry @SEQUOiA87 I totally forgot Angular in this case.

Maybe something can be done to detect if there's an Angular project and enable then push `typescript` in the array?

**Comment by max-programming** [comment]
Or I guess in the meantime, we could enable `typescript` while an issue like this persists?

**Comment by bradlc** [comment]
Yeah I think I'll revert this for now. Was already considering it since seeing #687 👍

**Pull request merged**
