### PR TITLE
tailwindcss-language-server: update lockfile

### PR DESCRIPTION
**Pull request by happysalada**
the lockfile is not up to date for tailwindcss-language-server, it doesn't contain vitest for some reason.

I'm packaging tailwindcss-language-server for nixos at the moment.

I can understand that a giant commit with a lockfille change is hard to trust, so if you prefer, feel free to just remove your lockfile and re-create it, that should do it.

Let me know if anything.

### CODE REVIEW

**Comment by reinink** [comment]
Hey thanks! I've updated a couple other lock files in this project and merged in it 🤙

**Comment by happysalada** [comment]
Thank you for your quick review!
Could you make another release when you have a moment ?
(for context, I'm packaging this for nixos. Ideally we use the source from a release). No big deal if you don't think it's time for a release yet, I can just use the latest master, just let me know.

**Comment by reinink** [comment]
@happysalada Hey you're quite welcome! So @bradlc generally takes care of doing the intellisense releases and he's on vacation this week, so the earliest we'll be able to get this out is next week. So I guess just use master for now 😊

**Comment by happysalada** [comment]
Thank you!
No worries, happy to wait for a week.
Thank you for your quick response.

**Comment by happysalada** [comment]
@bradlc could we get another release when you have a moment. This would includes fixes for the helix editor.

**Pull request merged**
