### PR TITLE
feature: add showColorEquivalents

### PR DESCRIPTION
**Pull request by zcqno1**
Hex format color is widely common use, but the tailwindcss-intellisense was just linting the rgba format color. The UI design often offers hex color, so it's tedious to give it a check to our color preset. With `showColorEquivalents` , the completion and hover tips will show the hex color as well.

### CODE REVIEW

**Comment by ahmadshiddiq** [comment]
This feature will be really cool to have, that make someone like me working much faster.
I need to check sometimes if the color code hex same like a Figma.

**Comment by janklimo** [comment]
@bradlc anything that needs to be done to get this released? This would be a lifesaver to have 👍 Happy to help!

**Comment by rabeehrz** [comment]
I literally looked up this repo to open an issue regarding this. Glad to see it already in the works. @bradlc Any way we could get this released?

**Comment by DjLait** [comment]
Any update on this feature?

**Comment by CruellyJoHn** [comment]
Any update on this feature?

**Comment by lukasvice** [comment]
I agree with the previous commentators. It would be very helpful if this PR could be merged.

**Comment by xsjcTony** [comment]
Any update? Bump.

**Comment by meirroth** [comment]
+1 just what I need

**Comment by matheusmb** [comment]
+1

**Comment by thecrypticace** [comment]
Resolved as part of merging #831. This feature is currently always on but we may add an option to toggle it in the future.

**Comment by meirroth** [comment]
I'm not seeing hex equivalents, is there a setting I need to enable? I'm using v0.10.5

**Pull request closed without merging**
