### PR TITLE
Add color format options (rgb, hex)

### LINKED ISSUE #418: Color Hex Code in intellisense box
Is it possible to add color hex code in the intellisense dialog?

image

I mean I wish that here I could see `#767676` beside `rgb(118, 118, 118)`.

The reason is that most of the time the developer get the hex code from the designer, with this we could speed up the development and better DX.

### PR DESCRIPTION
**Pull request by flostellbrink**
Formats are displayed in completions and as comments in hovered css. This helps with comparing code to designs.

This is basically an up to date version of #416 and fixes #418.

Makes it trivial to add more color formats going forward if people need them.

## Settings:
image

## Completions:
image

## Hovers:
image

### CODE REVIEW

**Comment by joaoprocopio** [comment]
I would absolutely LOVE this!

**Comment by flostellbrink** [comment]
Any feedback would be much appreciated @bradlc!

**Comment by xsjcTony** [comment]
Any update? Bump. This is really needed feature.

**Comment by AlexF090** [comment]
image
I don't understand why this feature is shown here even though it doesn't exist.
Or is there a hidden configuration option?

**Comment by numso** [comment]
I took the latest version (0.10.0) of this extension, applied this PR, and published it as a new vscode extension. I don't plan on maintaining it long term but my team couldn't wait any longer for this feature. Thought I'd post it here in case it helps anyone else.

https://marketplace.visualstudio.com/items?itemName=numso.vscode-tailwindcss-with-hex-colors

(aside: wouldn't it be amazing if you could use https://www.npmjs.com/package/patch-package on vscode extensions??)

**Comment by UNDERCOVERj** [comment]
mark

**Comment by Molunerfinn** [comment]
Very helpful

**Comment by Molunerfinn** [comment]
@thecrypticace Hope to merge this PR, it's very helpful

**Comment by GustavoSmith** [comment]
When will this be merged?

**Comment by federicocappellotto97** [comment]
+1, we need this please!!

**Comment by saymondamasio** [comment]
Someone merge the PR, please

**Comment by gustavo-mvp** [comment]
@flostellbrink resolve the conflicts please 🙏 
UP!

**Comment by flostellbrink** [comment]
Unfortunately a rebase is out of the questions at the moment. I need to test the changes, and master has been broken for three weeks straight now.

Either way I have no reason to believe anyone at tailwind actually wants this. Only leaving the PR open to avoid duplicate work.

**Comment by thecrypticace** [comment]
Hey, I'm going to be adding support for this but in a slightly different form. I think we can get rid of the color format option as well as simplify some things.

We're working on v4 right now but I expect I'll pick this back up possibly next week unless I happen to get to it sooner.

**Pull request merged**
