### PR TITLE
Add support for gohtmltmpl files for Hugo

### PR DESCRIPTION
**Pull request by dozyio**
Add support for gohtmltmpl files for [Hugo](https://gohugo.io/)

### CODE REVIEW

**Comment by bradlc** [comment]
Hey @dozyio. Which extension provides the `gohtmltmpl` language?

**Comment by dozyio** [comment]
Hi @bradlc,

https://github.com/fatih/vim-go provides the syntax and indentation for go html template files.

Hope that helps.

Thanks

**Comment by bradlc** [comment]
Thanks, I'm happy to merge this then!

**Comment by dozyio** [comment]
@bradlc brilliant, thank you!

**Pull request merged**
