### PR TITLE
Add support for twin.macro

### PR DESCRIPTION
**Pull request by lightyen**
According to #129 I try to add some code for [twin.macro](https://github.com/ben-rogerson/twin.macro).

### CODE REVIEW

**Comment by puneetverma05** [comment]
Hey @lightyen  thanks for the PR ✌ Any updates on this?

**Comment by dotomaz** [comment]
@lightyen 🙌 Any idea when will this be merged?

**Comment by locona** [comment]
@lightyen 🙌 Any idea when will this be merged?

**Comment by cheapsteak** [comment]
@puneetverma05  @locona @dotomaz y'all are pinging the wrong person, lightyen doesn't have the ability to merge into this repo

Based on the maintainer @bradlc 's message in https://github.com/tailwindlabs/tailwindcss-intellisense/issues/129 

> I am reluctant to hard-code each of these cases into the extension because none of them are "official" methods of using Tailwind, and it may become a maintenance burden.

>However, I am open to the idea of adding a user setting which would allow the definition of custom regular expressions. For example for tailwind-rn your regular expression might be something like: /\btailwind\([^)]+/ig

This leads me to believe that this PR might be unlikely to be merged as-is since it's hard-coding support for twins

**Comment by cheapsteak** [comment]
To solve this for twin users until #129 is resolved, might anyone want to package this branch into a separate vscode plugin and publish that? [already 12k weekly downloads and a strong momentum](https://npmcharts.com/compare/twin.macro), would do a lot of good

**Comment by Everspace** [comment]
I have attached a packaged vsix built at 28814afe953b712cad410e96173d9ee89ae59f17
[vscode-tailwindcss-0.4.4-0.zip](https://github.com/tailwindlabs/tailwindcss-intellisense/files/5400862/vscode-tailwindcss-0.4.4-0.zip)
Simply rename the extension from `zip` to `vsix` and in the command palette (`ctrl+shift+p`) find `Extensions: Install from VSIX...`

If you don't trust strangers on the internet, you may assemble and install the package yourself with the following:

```shell
git clone https://github.com/lightyen/tailwindcss-intellisense 
cd tailwindcss-intellisense
git fetch origin feature/twin.macro
git checkout feature/twin.macro
npm install
npm package
code --install vscode-tailwindcss-0.4.4-0.vsix
```

**Comment by ben-rogerson** [comment]
> @cheapsteak I have attached a packaged vsix built at [28814af](https://github.com/tailwindlabs/tailwindcss-intellisense/commit/28814afe953b712cad410e96173d9ee89ae59f17)
> [vscode-tailwindcss-0.4.4-0.zip](https://github.com/tailwindlabs/tailwindcss-intellisense/files/5400862/vscode-tailwindcss-0.4.4-0.zip)
> Simply rename the extension from `zip` to `vsix` and in the command palette (`ctrl+shift+p`) find `Extensions: Install from VSIX...`
> 
> If you don't trust strangers on the internet, you may assemble and install the package yourself with the following:
> 
> ```shell
> git clone https://github.com/lightyen/tailwindcss-intellisense 
> cd tailwindcss-intellisense
> git fetch origin feature/twin.macro
> git checkout feature/twin.macro
> npm install
> npm package
> code --install vscode-tailwindcss-0.4.4-0.vsix
> ```

The end instructions didn't work for me, here's what I ran:

```js
git clone https://github.com/lightyen/tailwindcss-intellisense
cd tailwindcss-intellisense
git fetch origin feature/twin.macro
git checkout feature/twin.macro
npm install
npx vsce package
```

Then in vscode, I used install `Extensions: Install from VSIX...`

Works great!

**Comment by Everspace** [comment]
@ben-rogerson that is because I forgot npm requires run to do a script

**Comment by rvion** [comment]
for those trying to follow above instruction to make a release, please note that lightyen renamed the repository to https://github.com/lightyen/vscode-tailwindcss-twin . Also note that this fork seems to be actively maintained.

**Pull request closed without merging**
